cmake_minimum_required(VERSION 3.16)
project(feetech_ros2_driver LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(hardware_interface REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
add_library(feetech_ros2_driver SHARED src/sim_feetech_hardware.cpp)
ament_target_dependencies(feetech_ros2_driver hardware_interface pluginlib rclcpp rclcpp_lifecycle)
pluginlib_export_plugin_description_file(hardware_interface feetech_ros2_driver.xml)
install(TARGETS feetech_ros2_driver LIBRARY DESTINATION lib)
ament_package()
